### ISSUE TITLE
Custom wp-content location

### ISSUE THREAD

**Issue by szepeviktor** [emrikol/focus#18]
https://github.com/emrikol/focus/blob/master/includes/object-cache.php#L409
The wp-content directory may have a custom location.

`WP_CONTENT_DIR` maybe?

**Comment by szepeviktor** [comment]
Thank you.

**Comment by emrikol** [comment]
Fixed in 1c49c27e62574e3115a924caa5955d7cbf62c9ff

**Comment by szepeviktor** [comment]
Thanks.
When do you expect to release v1.0.2?
