### ISSUE TITLE
Repo link

### ISSUE THREAD

**Issue by szepeviktor** [emrikol/focus#19]
Please add a repo link here on GitHub
https://wordpress.org/plugins/focus-object-cache/

**Comment by szepeviktor** [comment]
@emrikol Could you help setting it?

**Comment by emrikol** [comment]
@szepeviktor Do you mean in the readme.md?

**Comment by szepeviktor** [comment]
If you have the rights you see an <kbd>Ediot</kbd> button up here https://github.com/emrikol/focus

**Comment by emrikol** [comment]
Ahh, you mean here?

![image](https://user-images.githubusercontent.com/3060583/29125603-3b51be5a-7cea-11e7-9334-769648cc7914.png)

Sounds good to me :)

**Comment by szepeviktor** [comment]
See on my fork https://github.com/szepeviktor/focus
