### ISSUE TITLE
Unnecessary double sanitisation and double unslashing

### ISSUE THREAD

**Issue by david-binda** [emrikol/focus#3]
The code in `FOCUS_Cache::render_admin_page` is double sanitising the `$action` variable via `sanitize_text_field`.

First in https://github.com/emrikol/FOCUS/blob/master/focus-cache.php#L126 and for second time in https://github.com/emrikol/FOCUS/blob/master/focus-cache.php#L130

It's really needed only once.

Further, the double `wp_unslash` call may actually introduce some unwanted bugs. Eg.:

```
wp> addslashes( "O\'Reilly" );
string(11) "O\\\'Reilly"
wp> wp_unslash( "O\\\'Reilly" );
string(9) "O\'Reilly"
wp> wp_unslash( "O\'Reilly" );
string(8) "O'Reilly"
```

**Comment by emrikol** [comment]
Hopefully fixed by #6 :)
