### ISSUE TITLE
Unnecessary sanitisation and unslashing of nonce

### ISSUE THREAD

**Issue by david-binda** [emrikol/focus#4]
The `FOCUS_Cache::render_admin_page` is sanitising the `$nonce` variable using `wp_sanitize_text_field` and `wp_unslash`. By default, the nonce should not contain any character which would need any slashes or sanitisation (it should be md5 hash) and not even the WordPress core is sanitising the nonces, as they are invalid already, if they need some sanitisation.

See https://github.com/WordPress/WordPress/search?utf8=%E2%9C%93&q=wp_verify_nonce

**Comment by david-binda** [comment]
The same applies to `FOCUS_Cache::do_admin_action`

**Comment by emrikol** [comment]
Hopefully fixed by #6 :)
