### ISSUE TITLE
user input used in `add_query_arg` should be rawurlencode'd

### ISSUE THREAD

**Issue by david-binda** [emrikol/focus#5]
Use `rawurlencode` for sanitising the user input used by `add_query_arg` function.

* https://github.com/emrikol/FOCUS/blob/ef67d048f4a5bf3f144609edf63fbbf72c11a267/focus-cache.php#L133

* https://github.com/emrikol/FOCUS/blob/ef67d048f4a5bf3f144609edf63fbbf72c11a267/focus-cache.php#L304

* https://github.com/emrikol/FOCUS/blob/ef67d048f4a5bf3f144609edf63fbbf72c11a267/focus-cache.php#L332

**Comment by emrikol** [comment]
@david-binda Should `rawurlencode()` be used even though `add_query_arg()` calls `urlencode_deep()` on the arguments?

**Comment by emrikol** [comment]
Hopefully fixed by #6 :)
